export const TEACHER_API_RESULT = {
   "id":1,
   "name":"Lead Associated School",
   "schoolClasses":[
      {
         "id":1,
         "name":"Nursery",
         "school_id":1,
         "classSubjects":[
            {
               "id":2,
               "name":"Stories",
               "school_class_id":1,
               "subjectChapters":[
                  {
                     "id":3,
                     "name":"Historical Stories",
                     "class_subject_id":2,
                     "synopsis":[
                        {
                           "id":3,
                           "content":"http://www.africau.edu/images/default/sample.pdf",
                           "subject_chapter_id":3,
                           "synopsisBlobs":[
                              {
                                 "id":6,
                                 "language":"HINDI",
                                 "synopsis_id":3,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":5,
                                 "language":"ENGLISH",
                                 "synopsis_id":3,
                                 "link":"/home/leadschool_dev/dev/hackathon/smart-tutor-backend/audios/class6_science.m4a",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  },
                  {
                     "id":4,
                     "name":"Patriotism Stories",
                     "class_subject_id":2,
                     "synopsis":[
                        {
                           "id":4,
                           "content":"http://www.africau.edu/images/default/sample.pdf",
                           "subject_chapter_id":4,
                           "synopsisBlobs":[
                              {
                                 "id":7,
                                 "language":"ENGLISH",
                                 "synopsis_id":4,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":8,
                                 "language":"HINDI",
                                 "synopsis_id":4,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  }
               ]
            },
            {
               "id":1,
               "name":"Rhymes",
               "school_class_id":1,
               "subjectChapters":[
                  {
                     "id":1,
                     "name":"English Poem",
                     "class_subject_id":1,
                     "synopsis":[
                        {
                           "id":1,
                           "content":"https://dev2d-nucleus.leadschool.in/pdfs/audios/nursery_rhymes.pdf",
                           "subject_chapter_id":1,
                           "synopsisBlobs":[
                              {
                                 "id":1,
                                 "language":"ENGLISH",
                                 "synopsis_id":1,
                                 "link":"https://dev2d-nucleus.leadschool.in/pdfs/audios/nursery_rhymes.m4a",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  },
                  {
                     "id":2,
                     "name":"Hindi Poem",
                     "class_subject_id":1,
                     "synopsis":[
                        {
                           "id":2,
                           "content":"/home/leadschool_dev/dev/hackathon/smart-tutor-backend/audios/nursery_rhymes.pdf",
                           "subject_chapter_id":2,
                           "synopsisBlobs":[
                              {
                                 "id":3,
                                 "language":"ENGLISH",
                                 "synopsis_id":2,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":4,
                                 "language":"HINDI",
                                 "synopsis_id":2,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  }
               ]
            }
         ]
      },
      {
         "id":2,
         "name":"Class 6",
         "school_id":1,
         "classSubjects":[
            {
               "id":3,
               "name":"Science",
               "school_class_id":2,
               "subjectChapters":[
                  {
                     "id":6,
                     "name":"Food Components",
                     "class_subject_id":3,
                     "synopsis":[
                        {
                           "id":6,
                           "content":"http://www.africau.edu/images/default/sample.pdf",
                           "subject_chapter_id":6,
                           "synopsisBlobs":[
                              {
                                 "id":11,
                                 "language":"ENGLISH",
                                 "synopsis_id":6,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":12,
                                 "language":"HINDI",
                                 "synopsis_id":6,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  },
                  {
                     "id":5,
                     "name":"Body Movement",
                     "class_subject_id":3,
                     "synopsis":[
                        {
                           "id":5,
                           "content":"https://dev2d-nucleus.leadschool.in/pdfs/audios/class6_science.pdf",
                           "subject_chapter_id":5,
                           "synopsisBlobs":[
                              {
                                 "id":9,
                                 "language":"ENGLISH",
                                 "synopsis_id":5,
                                 "link":"https://dev2d-nucleus.leadschool.in/pdfs/audios/class6_science.m4a",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  }
               ]
            },
            {
               "id":4,
               "name":"EVS",
               "school_class_id":2,
               "subjectChapters":[
                  {
                     "id":7,
                     "name":"Parts of the body",
                     "class_subject_id":4,
                     "synopsis":[
                        {
                           "id":7,
                           "content":"http://www.africau.edu/images/default/sample.pdf",
                           "subject_chapter_id":7,
                           "synopsisBlobs":[
                              {
                                 "id":13,
                                 "language":"ENGLISH",
                                 "synopsis_id":7,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":14,
                                 "language":"HINDI",
                                 "synopsis_id":7,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  },
                  {
                     "id":8,
                     "name":"Introduction to traffic rules & safety",
                     "class_subject_id":4,
                     "synopsis":[
                        {
                           "id":8,
                           "content":"http://www.africau.edu/images/default/sample.pdf",
                           "subject_chapter_id":8,
                           "synopsisBlobs":[
                              {
                                 "id":15,
                                 "language":"ENGLISH",
                                 "synopsis_id":8,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":16,
                                 "language":"HINDI",
                                 "synopsis_id":8,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  }
               ]
            }
         ]
      },
      {
         "id":3,
         "name":"Class 7",
         "school_id":1,
         "classSubjects":[
            {
               "id":6,
               "name":"Nutrition",
               "school_class_id":3,
               "subjectChapters":[
                  {
                     "id":10,
                     "name":"Parts of the body",
                     "class_subject_id":6,
                     "synopsis":[
                        {
                           "id":10,
                           "content":"http://www.africau.edu/images/default/sample.pdf",
                           "subject_chapter_id":10,
                           "synopsisBlobs":[
                              {
                                 "id":19,
                                 "language":"ENGLISH",
                                 "synopsis_id":10,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":20,
                                 "language":"HINDI",
                                 "synopsis_id":10,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  }
               ]
            },
            {
               "id":5,
               "name":"Science",
               "school_class_id":3,
               "subjectChapters":[
                  {
                     "id":9,
                     "name":"Waste Water Management",
                     "class_subject_id":5,
                     "synopsis":[
                        {
                           "id":9,
                           "content":"https://dev2d-nucleus.leadschool.in/pdfs/audios/class7_science.pdf",
                           "subject_chapter_id":9,
                           "synopsisBlobs":[
                              {
                                 "id":17,
                                 "language":"ENGLISH",
                                 "synopsis_id":9,
                                 "link":"https://dev2d-nucleus.leadschool.in/pdfs/audios/class7_science.m4a",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  }
               ]
            }
         ]
      },
      {
         "id":5,
         "name":"SKG",
         "school_id":1,
         "classSubjects":[
            {
               "id":9,
               "name":"Science",
               "school_class_id":5,
               "subjectChapters":[
                  {
                     "id":11,
                     "name":"Motion",
                     "class_subject_id":9,
                     "synopsis":[
                        {
                           "id":11,
                           "content":"http://www.africau.edu/images/default/sample.pdf",
                           "subject_chapter_id":11,
                           "synopsisBlobs":[
                              {
                                 "id":21,
                                 "language":"ENGLISH",
                                 "synopsis_id":11,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":22,
                                 "language":"HINDI",
                                 "synopsis_id":11,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  },
                  {
                     "id":12,
                     "name":"Force",
                     "class_subject_id":9,
                     "synopsis":[
                        {
                           "id":12,
                           "content":"http://www.africau.edu/images/default/sample.pdf",
                           "subject_chapter_id":12,
                           "synopsisBlobs":[
                              {
                                 "id":23,
                                 "language":"ENGLISH",
                                 "synopsis_id":12,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":24,
                                 "language":"HINDI",
                                 "synopsis_id":12,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  },
                  {
                     "id":13,
                     "name":"Work",
                     "class_subject_id":9,
                     "synopsis":[
                        {
                           "id":13,
                           "content":"http://www.africau.edu/images/default/sample.pdf",
                           "subject_chapter_id":13,
                           "synopsisBlobs":[
                              {
                                 "id":25,
                                 "language":"ENGLISH",
                                 "synopsis_id":13,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":26,
                                 "language":"HINDI",
                                 "synopsis_id":13,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  }
               ]
            },
            {
               "id":10,
               "name":"Social Science",
               "school_class_id":5,
               "subjectChapters":[
                  {
                     "id":14,
                     "name":"Democratic Politics",
                     "class_subject_id":10,
                     "synopsis":[
                        {
                           "id":14,
                           "content":"http://www.africau.edu/images/default/sample.pdf",
                           "subject_chapter_id":14,
                           "synopsisBlobs":[
                              {
                                 "id":27,
                                 "language":"ENGLISH",
                                 "synopsis_id":14,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              },
                              {
                                 "id":28,
                                 "language":"HINDI",
                                 "synopsis_id":14,
                                 "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                 "type":"LEAD"
                              }
                           ]
                        }
                     ]
                  }
               ]
            }
         ]
      },
      {
         "id":4,
         "name":"JKG",
         "school_id":1,
         "classSubjects":[
            {
               "id":7,
               "name":"Hindi",
               "school_class_id":4,
               "subjectChapters":[
                  
               ]
            },
            {
               "id":8,
               "name":"English",
               "school_class_id":4,
               "subjectChapters":[
                  
               ]
            }
         ]
      }
   ]
}

export const STUDENT_API_RESULT = {
   "classSubjects" : [
      {
         "id":1,
         "name":"Rhymes",
         "school_class_id":1,
         "subjectChapters":[
            {
               "id":1,
               "name":"English Poem",
               "class_subject_id":1,
               "synopsis":[
                  {
                     "id":1,
                     "content":"https://dev2d-nucleus.leadschool.in/pdfs/audios/nursery_rhymes.pdf",
                     "subject_chapter_id":1,
                     "synopsisBlobs":[
                        {
                           "id":1,
                           "language":"ENGLISH",
                           "synopsis_id":1,
                           "link":"https://dev2d-nucleus.leadschool.in/pdfs/audios/nursery_rhymes.m4a",
                           "type":"LEAD"
                        }
                     ]
                  }
               ]
            },
            {
               "id":2,
               "name":"Hindi Poem",
               "class_subject_id":1,
               "synopsis":[
                  {
                     "id":2,
                     "content":"/home/leadschool_dev/dev/hackathon/smart-tutor-backend/audios/nursery_rhymes.pdf",
                     "subject_chapter_id":2,
                     "synopsisBlobs":[
                        {
                           "id":3,
                           "language":"ENGLISH",
                           "synopsis_id":2,
                           "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                           "type":"LEAD"
                        },
                        {
                           "id":4,
                           "language":"HINDI",
                           "synopsis_id":2,
                           "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                           "type":"LEAD"
                        }
                     ]
                  }
               ]
            }
         ]
      },
      {
         "id":5,
         "name":"Science",
         "school_class_id":3,
         "subjectChapters":[
            {
               "id":9,
               "name":"Waste Water Management",
               "class_subject_id":5,
               "synopsis":[
                  {
                     "id":9,
                     "content":"https://dev2d-nucleus.leadschool.in/pdfs/audios/class7_science.pdf",
                     "subject_chapter_id":9,
                     "synopsisBlobs":[
                        {
                           "id":17,
                           "language":"ENGLISH",
                           "synopsis_id":9,
                           "link":"https://dev2d-nucleus.leadschool.in/pdfs/audios/class7_science.m4a",
                           "type":"LEAD"
                        }
                     ]
                  }
               ]
            }
         ]
      },
      {
         "id":6,
         "name":"Nutrition",
         "school_class_id":3,
         "subjectChapters":[
            {
               "id":10,
               "name":"Parts of the body",
               "class_subject_id":6,
               "synopsis":[
                  {
                     "id":10,
                     "content":"http://www.africau.edu/images/default/sample.pdf",
                     "subject_chapter_id":10,
                     "synopsisBlobs":[
                        {
                           "id":19,
                           "language":"ENGLISH",
                           "synopsis_id":10,
                           "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                           "type":"LEAD"
                        },
                        {
                           "id":20,
                           "language":"HINDI",
                           "synopsis_id":10,
                           "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                           "type":"LEAD"
                        }
                     ]
                  }
               ]
            }
         ]
      },
      {
         "id":3,
         "name":"Human Sciences",
         "school_class_id":2,
         "subjectChapters":[
            {
               "id":6,
               "name":"Food Components",
               "class_subject_id":3,
               "synopsis":[
                  {
                     "id":6,
                     "content":"http://www.africau.edu/images/default/sample.pdf",
                     "subject_chapter_id":6,
                     "synopsisBlobs":[
                        {
                           "id":11,
                           "language":"ENGLISH",
                           "synopsis_id":6,
                           "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                           "type":"LEAD"
                        },
                        {
                           "id":12,
                           "language":"HINDI",
                           "synopsis_id":6,
                           "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                           "type":"LEAD"
                        }
                     ]
                  }
               ]
            },
            {
               "id":5,
               "name":"Body Movement",
               "class_subject_id":3,
               "synopsis":[
                  {
                     "id":5,
                     "content":"https://dev2d-nucleus.leadschool.in/pdfs/audios/class6_science.pdf",
                     "subject_chapter_id":5,
                     "synopsisBlobs":[
                        {
                           "id":9,
                           "language":"ENGLISH",
                           "synopsis_id":5,
                           "link":"https://dev2d-nucleus.leadschool.in/pdfs/audios/class6_science.m4a",
                           "type":"LEAD"
                        }
                     ]
                  }
               ]
            }
         ]
      },
      {
         "id":4,
         "name":"EVS",
         "school_class_id":2,
         "subjectChapters":[
            {
               "id":7,
               "name":"Parts of the body",
               "class_subject_id":4,
               "synopsis":[
                  {
                     "id":7,
                     "content":"http://www.africau.edu/images/default/sample.pdf",
                     "subject_chapter_id":7,
                     "synopsisBlobs":[
                        {
                           "id":13,
                           "language":"ENGLISH",
                           "synopsis_id":7,
                           "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                           "type":"LEAD"
                        },
                        {
                           "id":14,
                           "language":"HINDI",
                           "synopsis_id":7,
                           "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                           "type":"LEAD"
                        }
                     ]
                  }
               ]
            },
            {
               "id":8,
               "name":"Introduction to traffic rules & safety",
               "class_subject_id":4,
               "synopsis":[
                  {
                     "id":8,
                     "content":"http://www.africau.edu/images/default/sample.pdf",
                     "subject_chapter_id":8,
                     "synopsisBlobs":[
                        {
                           "id":15,
                           "language":"ENGLISH",
                           "synopsis_id":8,
                           "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                           "type":"LEAD"
                        },
                        {
                           "id":16,
                           "language":"HINDI",
                           "synopsis_id":8,
                           "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                           "type":"LEAD"
                        }
                     ]
                  }
               ]
            }
         ]
      }
   ]
}