export const TEACHER_API_RESULT = {
    "id":1,
    "name":"LeadAssociatedSchool",
    "schoolClasses":[
       {
          "id":1,
          "name":"Nursery",
          "school_id":1,
          "classSubjects":[
             {
                "id":1,
                "name":"Rhymes",
                "school_class_id":1,
                "subjectChapters":[
                   {
                      "id":1,
                      "name":"EnglishPoem",
                      "class_subject_id":1,
                      "synopsis":[
                         {
                            "id":1,
                            "content":"Pdfs/6.pdf",
                            "subject_chapter_id":1,
                            "synopsisBlobs":[
                               {
                                  "id":1,
                                  "language":"ENGLISH",
                                  "synopsis_id":1,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":2,
                                  "language":"HINDI",
                                  "synopsis_id":1,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   },
                   {
                      "id":2,
                      "name":"HindiPoem",
                      "class_subject_id":1,
                      "synopsis":[
                         {
                            "id":2,
                            "content":"Pdfs/7.pdf",
                            "subject_chapter_id":2,
                            "synopsisBlobs":[
                               {
                                  "id":3,
                                  "language":"ENGLISH",
                                  "synopsis_id":2,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":4,
                                  "language":"HINDI",
                                  "synopsis_id":2,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   }
                ]
             },
             {
                "id":2,
                "name":"Stories",
                "school_class_id":1,
                "subjectChapters":[
                   {
                      "id":3,
                      "name":"HistoricalStories",
                      "class_subject_id":2,
                      "synopsis":[
                         {
                            "id":3,
                            "content":"Pdfs/nursery.pdf",
                            "subject_chapter_id":3,
                            "synopsisBlobs":[
                               {
                                  "id":5,
                                  "language":"ENGLISH",
                                  "synopsis_id":3,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":6,
                                  "language":"HINDI",
                                  "synopsis_id":3,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   },
                   {
                      "id":4,
                      "name":"PatriotismStories",
                      "class_subject_id":2,
                      "synopsis":[
                         {
                            "id":4,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":4,
                            "synopsisBlobs":[
                               {
                                  "id":7,
                                  "language":"ENGLISH",
                                  "synopsis_id":4,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":8,
                                  "language":"HINDI",
                                  "synopsis_id":4,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   }
                ]
             }
          ]
       },
       {
          "id":2,
          "name":"JKG",
          "school_id":1,
          "classSubjects":[
             {
                "id":3,
                "name":"Mathematics",
                "school_class_id":2,
                "subjectChapters":[
                   {
                      "id":5,
                      "name":"Shapes",
                      "class_subject_id":3,
                      "synopsis":[
                         {
                            "id":5,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":5,
                            "synopsisBlobs":[
                               {
                                  "id":9,
                                  "language":"ENGLISH",
                                  "synopsis_id":5,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":10,
                                  "language":"HINDI",
                                  "synopsis_id":5,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   },
                   {
                      "id":6,
                      "name":"Count",
                      "class_subject_id":3,
                      "synopsis":[
                         {
                            "id":6,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":6,
                            "synopsisBlobs":[
                               {
                                  "id":11,
                                  "language":"ENGLISH",
                                  "synopsis_id":6,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":12,
                                  "language":"HINDI",
                                  "synopsis_id":6,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   }
                ]
             },
             {
                "id":4,
                "name":"EVS",
                "school_class_id":2,
                "subjectChapters":[
                   {
                      "id":7,
                      "name":"Partsofthebody",
                      "class_subject_id":4,
                      "synopsis":[
                         {
                            "id":7,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":7,
                            "synopsisBlobs":[
                               {
                                  "id":13,
                                  "language":"ENGLISH",
                                  "synopsis_id":7,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":14,
                                  "language":"HINDI",
                                  "synopsis_id":7,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   },
                   {
                      "id":8,
                      "name":"Introductiontotrafficrules&safety",
                      "class_subject_id":4,
                      "synopsis":[
                         {
                            "id":8,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":8,
                            "synopsisBlobs":[
                               {
                                  "id":15,
                                  "language":"ENGLISH",
                                  "synopsis_id":8,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":16,
                                  "language":"HINDI",
                                  "synopsis_id":8,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   }
                ]
             }
          ]
       },
       {
          "id":3,
          "name":"SKG",
          "school_id":1,
          "classSubjects":[
             {
                "id":5,
                "name":"Mathematics",
                "school_class_id":3,
                "subjectChapters":[
                   {
                      "id":9,
                      "name":"Numbers",
                      "class_subject_id":5,
                      "synopsis":[
                         {
                            "id":9,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":9,
                            "synopsisBlobs":[
                               {
                                  "id":17,
                                  "language":"ENGLISH",
                                  "synopsis_id":9,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":18,
                                  "language":"HINDI",
                                  "synopsis_id":9,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   }
                ]
             },
             {
                "id":6,
                "name":"GeneralAwareness",
                "school_class_id":3,
                "subjectChapters":[
                   {
                      "id":10,
                      "name":"Partsofthebody",
                      "class_subject_id":6,
                      "synopsis":[
                         {
                            "id":10,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":10,
                            "synopsisBlobs":[
                               {
                                  "id":19,
                                  "language":"ENGLISH",
                                  "synopsis_id":10,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":20,
                                  "language":"HINDI",
                                  "synopsis_id":10,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   }
                ]
             }
          ]
       },
       {
          "id":5,
          "name":"Class9",
          "school_id":1,
          "classSubjects":[
             {
                "id":9,
                "name":"Science",
                "school_class_id":5,
                "subjectChapters":[
                   {
                      "id":11,
                      "name":"Motion",
                      "class_subject_id":9,
                      "synopsis":[
                         {
                            "id":11,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":11,
                            "synopsisBlobs":[
                               {
                                  "id":21,
                                  "language":"ENGLISH",
                                  "synopsis_id":11,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":22,
                                  "language":"HINDI",
                                  "synopsis_id":11,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   },
                   {
                      "id":12,
                      "name":"Force",
                      "class_subject_id":9,
                      "synopsis":[
                         {
                            "id":12,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":12,
                            "synopsisBlobs":[
                               {
                                  "id":23,
                                  "language":"ENGLISH",
                                  "synopsis_id":12,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":24,
                                  "language":"HINDI",
                                  "synopsis_id":12,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   },
                   {
                      "id":13,
                      "name":"Work",
                      "class_subject_id":9,
                      "synopsis":[
                         {
                            "id":13,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":13,
                            "synopsisBlobs":[
                               {
                                  "id":25,
                                  "language":"ENGLISH",
                                  "synopsis_id":13,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":26,
                                  "language":"HINDI",
                                  "synopsis_id":13,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   }
                ]
             },
             {
                "id":10,
                "name":"SocialScience",
                "school_class_id":5,
                "subjectChapters":[
                   {
                      "id":14,
                      "name":"DemocraticPolitics",
                      "class_subject_id":10,
                      "synopsis":[
                         {
                            "id":14,
                            "content":"http://www.africau.edu/images/default/sample.pdf",
                            "subject_chapter_id":14,
                            "synopsisBlobs":[
                               {
                                  "id":27,
                                  "language":"ENGLISH",
                                  "synopsis_id":14,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               },
                               {
                                  "id":28,
                                  "language":"HINDI",
                                  "synopsis_id":14,
                                  "link":"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                                  "type":"LEAD"
                               }
                            ]
                         }
                      ]
                   }
                ]
             }
          ]
       },
       {
          "id":4,
          "name":"Class5",
          "school_id":1,
          "classSubjects":[
             {
                "id":7,
                "name":"Hindi",
                "school_class_id":4,
                "subjectChapters":[
                   
                ]
             },
             {
                "id":8,
                "name":"English",
                "school_class_id":4,
                "subjectChapters":[
                   
                ]
             }
          ]
       }
    ]
 }